version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./server
    env_file: ./server/.env.example
    ports:
      - '4000:4000'
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - '5173:80'
volumes:
  mongo-data:
